### ISSUE TITLE
CRAN checklist

### ISSUE THREAD

**Issue by layik** [tgve/tgver#11]
- [x] fails on Linux (sf package install)
- [x] [fails](https://builder.r-hub.io/status/original/tgver_0.1.1.tar.gz-ea3aae78ad3b450189a4ee35986d177f) on r-hub due to `browseURL` not finding any on runners
- [x] some weird [fail](https://builder.r-hub.io/status/original/tgver_0.1.1.tar.gz-482c5fdb89734d189d04fd303b94a2df) on r-hub due to `netbase` sys deps on Ubuntu and Fedora is thrown not being able to fetch a png from raw.githubusercontent

**Comment by layik** [comment]
`rhub` latest checks
``` r
setwd("/path/to/tgver/")
rhub::check_for_cran()
#> Warning: replacing previous import 'lifecycle::last_warnings' by
#> 'rlang::last_warnings' when loading 'pillar'
#> ─  Building package
#> ─  Uploading package
#> ─  Preparing build, see status at
#>    https://builder.r-hub.io/status/tgver_0.1.1.tar.gz-f50e1e6a213443a9b0fc8ab7f700e63a
#>    https://builder.r-hub.io/status/tgver_0.1.1.tar.gz-3414416f3f304438a486829d4dec9cba
#>    https://builder.r-hub.io/status/tgver_0.1.1.tar.gz-554a25bbaf494ab69f975e8346cc63ee
```

<sup>Created on 2022-02-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by layik** [comment]
Official guide:
https://cran.r-project.org/web/packages/submission_checklist.html

The R package book:
https://r-pkgs.org/release.html

**Comment by layik** [comment]
`rhub` is not happy with openURL I think https://builder.r-hub.io/status/tgver_0.1.1.tar.gz-554a25bbaf494ab69f975e8346cc63ee#L9984

**Comment by layik** [comment]
Next round of builds on `rhub`

* https://builder.r-hub.io/status/tgver_0.2.0.tar.gz-298c0eda6b4c4aa3b697143c66eca819
* https://builder.r-hub.io/status/tgver_0.2.0.tar.gz-18713cc73d884e41a38fdcda25aa5994
* https://builder.r-hub.io/status/tgver_0.2.0.tar.gz-fefd55a7cf924bd58b722cfe3162a40a

**Comment by layik** [comment]
Latest [error](https://builder.r-hub.io/status/tgver_0.2.0.tar.gz-18713cc73d884e41a38fdcda25aa5994) (still Linux only) from `rhub::check_for_cran()` is related to fetching content from github with some `ConnectionFailure Network.BSD.getProtocolByName: does not exist (no such protocol name: tcp)` error. So trying again.

**Comment by layik** [comment]
Now that `rhub` is failing only due to `notes`. There is only the [matter](https://r-pkgs.org/r-cmd-check.html)  of submitting to CRAN with install size note. We could solve this by trying to further trim the build by avoiding to include some other deps possibly creeping in unintentionally or finding workarounds.

**Comment by layik** [comment]
So a long Friday later. I have learned something that I perhaps should have known years/months ago. Our `tgve.zip` can be as small as 1.1mb now. Please see https://github.com/tgve/tgver/commit/1e0dece48b89c9c2293e0b90bf3887987c53469f and one that is coming to `tgve/app` soon.

**Comment by layik** [comment]
Final attempt at `rhub`. It is impossible to get rid of all NOTES or even errors on `rhub`.

**Comment by layik** [comment]
Pending #26 before running `devtools::submit_cran()`
